<?php
/**
 * @package mardiio-theme
 */
?>

<!DOCTYPE html>

<html <?php language_attributes(); ?>>
    <head>
        <meta charset="<?php bloginfo( 'charset' ); ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="profile" href="http://gmpg.org/xfn/11">

        <?php 
        // Check if the post is singular and the ping options is activated.
        if ( is_single() && pings_open( get_queried_object() ) ) {
        ?>
            <link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">            
        <?php
        }
        ?>

        <?php wp_head(); ?>
    </head>
    
    <!-- Class generated by WP to style the body -->
    <body <?php body_class(); ?>>
